# list manipulation - sictionary
DATA = {
               "CPU" : "EXECUTES INSTRUCTION" ,
               "HARDWARE" : "PHYSICAL PARTS" ,
               "SOFTWARE" : "PROGRAMS" ,
               "MOTHERBOARD" : "CONNECTS COMPONENETS" ,
               "RAM" : "TEMPORARY MEMORY" ,
               "ROM" : "PERMANENT MEMORY" ,
               "HDD" : "DATA STORAGE" ,
               "SDD" : "FAST STORAGE" ,
               "GPU" : "GRAPHICD PROCESSOR" ,
               "CACHE" : "QUICK MEMORY" ,
               "OS" : "MANAGES SYSTEM" ,
               "NETWORK" : "CONNECTED COMPUTER" ,
               "INTERNET" : "GLOBAL NETWORK" ,
               "CLOUD" : "ONLINE STORAGE" ,
               "FIRE WALL" : "BLOCK THREATS" ,
               "CYBERSECURITY" : "DIGITAL PROTECTION" ,
               "DATABASE" : "STORAGE DATA" ,
               "ALGORITHM" : "SOLVING STEPS" ,
               "PROGRAMMING" : "WRITING CODE" ,
               "CODING" : "SOFYWARE COMMANDS" ,
               "DEBUGGING" : "FIXING ERRORS" ,
               "INCRYPTION" : "SECURING DATA" ,
               "AI" : "SMART MACHINES" ,
               "MACHINE LEARNING" : "AI LEARNING" ,
               "VIRTUALIZATION" : "SIMULATED COMPUTING" ,
               "SERVER" : "PROVIDE SERVICES" ,
               "BIOS" : "BOOTS SYSTEM" ,
               "PERIPHERAL" : "EXTERNAL DEVICE" ,
               "BIT" : "SMALLEST DATA" ,
               "BYTE" : "8 BITS" ,
}